from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, Any, Optional


def _strip_quotes(s: str) -> str:
    s = s.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ("'", '"'):
        return s[1:-1]
    return s


def update_mesh_metadata_name(config_path: str | Path, new_name: str) -> Dict[str, Any]:
    """
    Update mesh: metadata: name in a CUE file generated by greymatter.
    This is a targeted edit (not a full CUE parser) designed to be stable
    for common "block-style" CUE with braces.
    """
    p = Path(config_path)
    if not p.exists():
        return {"returncode": 1, "stderr": f"config.cue not found: {p}"}

    text = p.read_text(encoding="utf-8")

    # Quick path: replace the first occurrence of mesh.metadata.name if it appears as a dotted field.
    dotted = re.compile(r'(?m)^\s*mesh\.metadata\.name\s*:\s*(".*?"|\'.*?\'|[^\s#]+)\s*(#.*)?$')
    m = dotted.search(text)
    if m:
        old = _strip_quotes(m.group(1))
        replaced = dotted.sub(lambda mm: mm.group(0).replace(mm.group(1), f'"{new_name}"', 1), text, count=1)
        p.write_text(replaced, encoding="utf-8")
        return {"returncode": 0, "stdout": f"updated mesh.metadata.name {old} -> {new_name}", "path": str(p)}

    # Block-style path: mesh: { metadata: { name: "..." } }
    # We do a conservative brace-scan:
    lines = text.splitlines(True)

    def find_block_start(key: str, start_idx: int = 0) -> Optional[int]:
        pat = re.compile(rf'^\s*{re.escape(key)}\s*:\s*{{\s*(#.*)?$')
        for i in range(start_idx, len(lines)):
            if pat.match(lines[i]):
                return i
        return None

    def find_matching_brace(open_idx: int) -> Optional[int]:
        depth = 0
        for i in range(open_idx, len(lines)):
            depth += lines[i].count("{")
            depth -= lines[i].count("}")
            if i > open_idx and depth <= 0:
                return i
        return None

    mesh_i = find_block_start("mesh")
    if mesh_i is None:
        return {"returncode": 1, "stderr": "mesh block not found"}

    mesh_end = find_matching_brace(mesh_i)
    if mesh_end is None:
        return {"returncode": 1, "stderr": "mesh block brace mismatch"}

    # Search metadata block inside mesh block
    meta_i = None
    meta_pat = re.compile(r'^\s*metadata\s*:\s*{\s*(#.*)?$')
    for i in range(mesh_i + 1, mesh_end + 1):
        if meta_pat.match(lines[i]):
            meta_i = i
            break
    if meta_i is None:
        return {"returncode": 1, "stderr": "metadata block not found under mesh"}

    meta_end = find_matching_brace(meta_i)
    if meta_end is None or meta_end > mesh_end:
        return {"returncode": 1, "stderr": "metadata block brace mismatch"}

    # Replace name inside metadata block
    name_pat = re.compile(r'(?m)^(\s*name\s*:\s*)(".*?"|\'.*?\'|[^\s#]+)(\s*(#.*)?)$')
    for i in range(meta_i + 1, meta_end + 1):
        m2 = name_pat.match(lines[i])
        if m2:
            old = _strip_quotes(m2.group(2))
            lines[i] = f'{m2.group(1)}"{new_name}"{m2.group(3) or ""}\n'
            p.write_text("".join(lines), encoding="utf-8")
            return {"returncode": 0, "stdout": f"updated mesh.metadata.name {old} -> {new_name}", "path": str(p)}

    return {"returncode": 1, "stderr": "name field not found under mesh.metadata"}
